name: mines_flutter
description: A Flutter Minesweeper.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/classic_image_00.png
   - assets/images/classic_image_01.png
   - assets/images/classic_image_02.png
   - assets/images/classic_image_03.png
   - assets/images/classic_image_04.png
   - assets/images/classic_image_05.png
   - assets/images/classic_image_06.png
   - assets/images/classic_image_07.png
   - assets/images/classic_image_08.png
   - assets/images/classic_image_09.png
   - assets/images/classic_image_10.png
   - assets/images/classic_image_11.png
   - assets/images/classic_image_12.png
   - assets/images/classic_image_13.png
   - assets/images/classic_image_14.png
   - assets/images/classic_image_15.png
   - assets/images/counter_0.gif
   - assets/images/counter_1.gif
   - assets/images/counter_2.gif
   - assets/images/counter_3.gif
   - assets/images/counter_4.gif
   - assets/images/counter_5.gif
   - assets/images/counter_6.gif
   - assets/images/counter_7.gif
   - assets/images/counter_8.gif
   - assets/images/counter_9.gif
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
